### ISSUE TITLE
GPU is not used in python wheel generated for GPU

### ISSUE THREAD

**Issue by mtrtn2u** [google/mediapipe#3353]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 18.04, Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):gcc/g++ 8
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python
- Installed using virtualenv? pip? Conda? (if python): venv
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.9
- Bazel version: 
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 4.5.5.64

**Describe the problem**:
I'm experiencing an unexpected behavior after successfully generating a .whl of mediapipe with the changes required to use the GPU according either to the solution proposed in issues #1651 or #3266. The build process is successful and I can pip install the .whl and run facemesh in python. The issue is that the CPU usage is unchanged (around 350% on a coupleryzen7 4000 series) compared to the CPU version and from GPU monitoring tools such as corectrl and nvidia-smi the GPU looks to be unused by the process. This behavior was encountered both on AMD RADEON and on NVIDIA GPU, both on Ubuntu 18.04 with python 3.6 and 3.8 and on Ubuntu 20.04 with python 3.8.
From the logs it looks like it is running the GPU graphs but this is inconsistent with the CPU and GPU activity monitored.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
After modding the code accordingly to #1651 or after installing mediapipe from the repo linked in #3266 I do the following steps:
1) I create a venv in the parent directory of mediapipe so that I have /parent/mediapipe and /parent/venv
python3 -m venv venv && source venv/bin/activate
2) I upgrade pip, install wheel and setuptools
pip install -U pip 
pip install wheel setuptools
3) I generate the protos and the wheel 
python setup.py gen_protos && python setup.py bdist_wheel
4)I install the wheel in the venv 
pip install mediapipe-dev-cp38-cp38-linux_x86_64.wheel
5)I successfully launch the basic mediapipe facemesh script as shown in the docs.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
This is the output of the bash shell after I launch a basic facemesh  script:

WARNING: Logging before InitGoogleLogging() is written to STDERR
I20220517 16:02:06.958925 93230 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20220517 16:02:06.969666 93260 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 Mesa 21.2.6)
I20220517 16:02:06.969858 93230 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20220517 16:02:06.971607 93262 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 Mesa 21.2.6)
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Replacing 164 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 97 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.

**Comment by sureshdagooglecom** [comment]
Hi @mtrtn2u ,
MediaPipe python solutions supports only for CPU graphs ,You can follow https://github.com/google/mediapipe/issues/1651#issuecomment-790176010 to run the GPU graphs. Sorry for the inconvenience.

**Comment by mtrtn2u** [comment]
Hi @sureshdagooglecom. That is exactly what I did to run the GPU graphs, maybe I've not been very clear. The issue is that the  procedure described in #1651 leads me to a wheel that does not use any GPU resources.

**Comment by mtrtn2u** [comment]
Is there anyone that can help with my issue? I've tried to generate again the wheel following once again #1651 but to no avail. @sureshdagooglecom  could you look into it?

**Comment by sergionocco** [comment]
Hi @mtrtn2u,
we actually had exactly the same problem in my team: we could successfully run mediapipe (actually, the face mesh solution) with the GPU features, but only using the original (c++) code. We tried as well to generate a python wheel, but apparently the software always went on the cpu only, no matter the modifications we applied on the code/compilation files. I really would appreciate if this issue could be solved, since we ended up with using mediapipe as a stand-alone tool...

**Comment by mtrtn2u** [comment]
UPDATE:
I went back as far as to version v0.8.3, with modifications to the graphs, BUILD and setup.py done accordingly to the calculators and stuff that version contains. The results are once again the same. CPU usage is always over 360% on ryzen7 series 4000. GPU usage both on Nvidia and AMD is none. I assume that those modifications , as in #1651,  only lead to a successful  build process that doesn't actually reflect on actual usage of GPU resources. If true hat would be a shame as the python wrapper is very much practical and straightforward to use.

**Comment by lghasemzadeh** [comment]
> Hi @mtrtn2u, we actually had exactly the same problem in my team: we could successfully run mediapipe (actually, the face mesh solution) with the GPU features, but only using the original (c++) code. We tried as well to generate a python wheel, but apparently the software always went on the cpu only, no matter the modifications we applied on the code/compilation files. I really would appreciate if this issue could be solved, since we ended up with using mediapipe as a stand-alone tool...

Hello @sergionocco,
Thanks for your comment. 
1. So, if I use the mediapipe face mesh original c++ code, I will be able to run it on GPU. is that right?
2. Did running on GPU increased the speed/FPS/performance?
I appreciate if you share you experience.

**Comment by sergionocco** [comment]
Hi @lghasemzadeh,

1. I think so, we properly modified the compilation files in order to run the GPU graphs, and yes, apparently with the original c++ code the GPU was indeed used (though the gpu usage percentage was anyhow quite small)
2. Yes, but not in the sense that you mean. The fact is that we had to process in real time a video stream with a low frame rate (about 10 Hz), but the full processing pipeline (acquisition + mediapipe + subsequent algorithms) had to run on an embedded system with small resources, something like a jetson nano. So, for us, it was important to save the processor usage by demanding what was possible to the gpu... and yes, doing it this way, the full on-board processing was possible.

**Comment by lghasemzadeh** [comment]
Thanks for the reply @sergionocco .
I am in same situation as you are :) I need to run my code efficiently on jetson nano.
we I run my algorithms locally on my desktop, I get this notification in terminal (INFO: Created TensorFlow Lite XNNPACK delegate for CPU) also I check the GPU and CPU usage and it seems it uses CPU most, the FPS is around 30.
But when I run the same codes on nano, without any modification in mediapipe instruction, I get the notification of using GPU! (INFO: Created TensorFlow Lite XNNPACK delegate for GPU) but when I check the usage it seems it is using CPU, not GPU. and the FPS for the same code is 6. FPS decreases dramatically and I get an undesired latency in my algorithm.
My questions are:
1. Without using c++, can I run my python codes on nano using GPU? 
2. If I am not mistaken you mentioned that you succeed to run python codes on GPU in the above comment. How you did that? would you please share?
3. have you tried the solution in this issue #3266?
Thanks

**Comment by sergionocco** [comment]
Well @lghasemzadeh, 
first of all, in my experience, running mediapipe with GPU support simply *reduces* the CPU usage, but, apparently, the big job is still performed by the main processor. To give you an idea, on my desktop pc, running mediapipe without the GPU gives a CPU usage around 130%, and it decreases to about 100% when the GPU is also enabled. Then:

1. ehm, I don't know, I guess this is the object of the issue opened by @mtrtn2u. We did run python codes on jetson nano, but subsequently to mediapipe, which indeed was executed as a stand-alone process using the original c++ code.
2. actually no, I said that we struggled to incorporate the mediapipe python byndings (with GPU support) in our scripts, but in the end we gave up, and finally ran mediapipe as a separate process.
3. well, not really, I will have a look, thank you for the link...

I hope this comment will be useful to you and to any other interested in this matter...

**Comment by mtrtn2u** [comment]
Hi @sergionocco and @lghasemzadeh. I have the feeling we are experiencing all the same issue. I want to be able to effectively run the gpu  python mediapipe version on jetson nano. Meanwhile I did find out that there was a collateral issue that bumped up my CPU consumption that high, but even after correcting that mediapipe in python still consumes an awful lot of CPU resources, indeed too much for a jetson nano.
As you may read in my original issue I too get the notification that mediapipe is using GPU (INFO: Created TensorFlow Lite XNNPACK delegate for GPU) but that doesn't reflect on actual GPU usage.
On the other hand implementing everything I need to do into a custom mediapipe solution in c++  is not practical at all thanks to Bazel that is cryptic to work with, to say the least.

**Comment by lghasemzadeh** [comment]
Actually I don't mind if CPU or GPU is under load. I only want to increase my algorithm FPS.
For my custom python algorithm which uses mediapipe, on jetson nano, I get FPS of 6, and for another mediapipe-based algorithm I get FPS of 2, they are really low and they are not suitable for real-time applications.
These algorithms have only bunch of simple mathematics calculation. the FPS shouldn't be that low, while on desktop I get 30 FPS. So I changed or deleted some of calculations in the code, and FPS increased. But this is not the correct way to aaproach this problem.
so I decided to use GPU to reduce the CPU usage which cause increasing FPS.

4. @sergionocco how you enabled GPU on desktop PC? I even want that slightly reduction of CPU usage.
5. @mtrtn2u what was the collateral issue you found? How you fixed it?

@[bossebandowski](https://github.com/bossebandowski) what do you think?

**Comment by mtrtn2u** [comment]
@lghasemzadeh  Unfortunately for me, I'd rather have mediapipe running on GPU because I need the CPU to be available for other hefty processes and as you mentioned 2 or even 6 FPS are definitely not enough. The collateral issue I had was with code that takes in input the face_landmarks from facemesh to compute geometrical features, so it is not really related to mediapipe per se. 
I close the issue as there seems to be no solution for it.

**Comment by bossebandowski** [comment]
@lghasemzadeh

Looks like this is getting a bit messy. Here's where we're at:

- We have not yet managed to run the python wrapper with mediapipe on any platform using the GPU.
- We are currently not looking at embedded systems but have done so in the past. This [repo](https://github.com/jiuqiant/mediapipe_python_aarch64) provides an installation guide for aarch64 architectures and we managed to get working builds, but again without using the GPU
- In general, there is no problem with using the GPU from python. Have you looked at other pose estimation frameworks? We played around with [trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose) which gets the job done at a much higher framerate, but the model performance seems to be worse.

**Comment by siyuzou** [comment]
@mtrtn2u 
Hi, I have encountered very similar issues, and somehow managed to figure it out.

I'm using ubuntu 22.04 with a Nvidia rtx3070 card, and I want to run mediapipe holistic model on GPU using python interface.

I modified those files (holistic landmark pbtxt, setup.py, BUILD, etc) as [#1651 (comment)](https://github.com/google/mediapipe/issues/1651#issuecomment-790176010) did, but on the newest `mediapipe-v0.8.11`, then successfully built a .whl, and pip installed it.
Executing it gives very similar logs like yours:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20221207 10:57:13.676404 77499 calculator_graph.cc:123] Initialize the GPU.
I20221207 10:57:13.694615 77499 gl_context_egl.cc:84] Successfully initialized EGL. Major : 1 Minor: 5
I20221207 10:57:13.705412 77575 gl_context.cc:335] GL version: 3.2 (OpenGL ES 3.2 Mesa 22.0.5)
I20221207 10:57:13.705475 77499 calculator_graph.cc:127] Succeeded get GPU
INFO: Created TensorFlow Lite delegate for GPU.
```
In this case, mediapipe holistic on this "GPU" version runs much slower than on CPU version (~70 ms on "GPU" vs ~30 ms on CPU), and of course `nvidia-smi` confirms that no gpu is using.

Then I found this [comment](https://github.com/google/mediapipe/issues/3266#issuecomment-1134497847), the replier succesfully runs mediapipe using python interface on GPU. You can see that the OpenGL runs on Nvidia libs, but not Mesa libs:
```
I20220523 19:14:59.332114 556636 gl_context.cc:334] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 470.129.06)
```

You can also check this by using `glxinfo` (the [official doc](https://google.github.io/mediapipe/getting_started/gpu_support.html) also mentioned it, and you can see that Nvidia libs are used.)

I'm not familiar with these GL stuffs, but I found out that my ubuntu use intel graphic card as default. and I switched it to nvidia graphic card using `prime-select`:
```bash
sudo apt-get install nvidia-prime
prime-select nvidia
reboot
```
and it works in my environment. The log shows that OpenGL runs on Nvidia libs now:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20221208 15:04:13.921077 113265 gl_context_egl.cc:86] Successfully initialized EGL. Major : 1 Minor: 5
I20221208 15:04:13.957674 113332 gl_context.cc:335] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 515.48.07)
I20221208 15:04:13.957754 113265 gl_context_egl.cc:86] Successfully initialized EGL. Major : 1 Minor: 5
I20221208 15:04:13.969427 113333 gl_context.cc:335] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 515.48.07)
INFO: Created TensorFlow Lite delegate for GPU.
```
Mediapipe holistic python interface now runs 15ms per frame on my machine (compared to 30ms per frame on CPU).

**Comment by mtritto** [comment]
@siyuzou thanks for your insight. I have since moved on from this topic given the not so good results I was getting. Your workaround looks worth one more attempt, I will report back once I manage to try it.

**Comment by mtrtn2u** [comment]
@siyuzou I since put aside this topic given the results I was getting were not what I expected but your workaround look worth one more attempt. I will try it out and report back if it works. Thanks for your insight.

**Comment by nikitax75** [comment]
@siyuzou would you be able to share your modifications for `v0.8.11`? I am trying to reproduce the very same setup. Thanks in advance!
