### ISSUE TITLE
C++ GPU Example Doesn't Appear to Use the GPU

### ISSUE THREAD

**Issue by n-iwamoto** [google/mediapipe#4156]
### OS Platform and Distribution

GCP VM Instance

### Compiler version

gcc-8 & g++-8

### Programming Language and version

C++

### Installed using virtualenv? pip? Conda?(if python)

venv & pip install tensorflow==2.11.* (not conda)

### MediaPipe version

0.8.10

### Bazel version

5.2.0

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.19

### Describe the problem

```shell
NOTE: this was run in a GCP VM Instance w/n1-standard-8, and 1 x NVIDIA T4. This is the environment that we need to run in.

Installed MediaPipe according to documentation, and ran example CPU & GPU applications w/no problem. However, running "nvidia-smi --query-gpu=utilization.gpu --format=csv --loop=1" shows 0% GPU utilization.

Followed this for installation & running examples (both CPU & GPU examples work):

https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu  
https://google.github.io/mediapipe/getting_started/cpp.html

For the C++ GPU example, used input & output files since there is no attached camera:

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt --input_video_path=docs/images/selfie_segmentation_web.mp4 --output_video_path=/tmp/vidout.mp4

selfie_segmentation_web.mp4 file was from: 
https://github.com/google/mediapipe/tree/v0.8.10/docs/images/selfie_segmentation.html

/tmp/vidout.mp4 file showed that hand tracking worked, but GPU showed 0% utilization.

I also installed TensorFlow examples to make sure the GPU was discovered (did not use conda, used pip install tensorflow==2.11.* instead):

https://www.tensorflow.org/install/pip#software_requirements

Output from "python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"":

2023-03-08 19:59:04.550642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 11970 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
tf.Tensor(1325.5834, shape=(), dtype=float32)

Output from "python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"":

2023-03-08 19:59:18.542401: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

I suspect that I'm doing something wrong, or the environment I'm running in is incompatible somehow. Any help would be greatly appreciated.

Thanks
```

### Complete Logs

```shell
Running the C++ GPU HandTracking example, /tmp/vidout.mp4 file showed that hand tracking worked, but GPU showed 0% utilization.

From TensorFlow setup tests:
Output from "python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"":

2023-03-08 19:59:04.550642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 11970 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
tf.Tensor(1325.5834, shape=(), dtype=float32)

Output from "python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"":

2023-03-08 19:59:18.542401: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by ayushgdev** [comment]
Hello @n-iwamoto These are quite interesting observations. We appreciate the time spent on the analysis of the issue across different solutions. 
Please allow us sometime to replicate the issue at our end and provide any comments.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , forgot to include that:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , just wondering if you might have had a chance to look at this to see if you are able to replicate what I'm seeing.

Also, just to check, do I need to be using CUDA to run that example? I'm resuming not since the --config=cuda flag isn't used in the example. However, I haven't been able to get the CUDA GPU example working (https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop); getting a compile error -- I'm not very familiar w/bazel:

ERROR: An error occurred during the fetch of repository 'local_config_cuda'

I have CUDA 11.7 installed, and copied the following into my .bazelrc file:

# This config refers to building CUDA op kernels with nvcc.
build:cuda --repo_env TF_NEED_CUDA=1
build:cuda --crosstool_top=@local_config_cuda//crosstool:toolchain
build:cuda --@local_config_cuda//:enable_cuda

# This config refers to building CUDA op kernels with clang.
build:cuda_clang --config=cuda
build:cuda_clang --repo_env TF_CUDA_CLANG=1
build:cuda_clang --@local_config_cuda//:cuda_compiler=clang

I tried modifying the WORKSPACE file to add local_config_cuda, but that didn't work.

**Comment by ayushgdev** [comment]
Hello @n-iwamoto 

Apologies for the delay. The setup for GPU takes time to get running since there are many gears to the machine. However, regarding the issue of GPU not being used, the issue is not reproducible at our end. Please refer the screenshot attached.
<img width="875" alt="Screenshot 2023-03-28 at 1 06 36 PM" src="https://user-images.githubusercontent.com/118424249/228162995-cc190e20-addb-4896-8b17-bede332cfdcf.png">


Regarding GPU usage and CUDA, quoting from the docs:
> MediaPipe framework doesn't require CUDA for GPU _compute and rendering_. However, MediaPipe can work with TensorFlow to perform GPU inference on video cards that support CUDA.

1. Please make sure you follow the guide for GPU setup as provided [here.](https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop) Although there was one difference in the GPU setup. The [GPU driver installation docs of GCP](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu) were used rather than Tensorflow docs for GPU driver installation since the exact version of CUDA needed for the setup of each GPU model is easily provided there. 
2. CUDA 10.1 was used using commands [here](https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal).
3. Also, please ensure to complete [Post installation Actions](https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html#post-installation-actions) as well for CUDA before moving on to the cuDNN SDK installation. Otherwise the Nvidia Drivers were not recognized for our setup.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , thanks so much for confirming that this works, appreciate it!

Just want to confirm your environment compared to mine (so I can make the changes to get this to work). My environment & tools:
- GPU used: T4
- Ubuntu 18.04
- gcc-8 & g++-8
- MP branch: 0.8.10
- Bazel version: 5.2.0
- OpenCV: 3.4.19
- Nvidia driver version: 515.65.01
- CUDA version: 11.7 <-- other folks require this version on the GCP instance
- OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8

I see from your response above that CUDA isn't necessary to run MP w/GPU, so I wondering if your instructions on setting up CUDA was just to answer my question above, or was it needed to get MP to use GPU in the GCP instance; i.e. did you compile w/the CUDA option (e.g. bazel build -c opt --config=cuda)? Or did you just use this build command?

bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

**Comment by ayushgdev** [comment]
Hello @n-iwamoto 
You can find the details of the GCP instance used in the screenshot below. PS: I am unable to print the OpenGL ES profile information. with glxinfo command, I am getting error `Error: unable to open display`. 
We would suggest using opencv version 3.2 as per the MediaPipe [docs](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_debian_and_ubuntu). Also, the code was tested with MP version 0.9.2(latest) so probably you can try with that version. MediaPipe is yet in alpha release so each version can introduce many changes. 

<img width="1481" alt="Screenshot 2023-03-29 at 4 42 14 PM" src="https://user-images.githubusercontent.com/118424249/228518250-0729b73d-153f-4935-9102-55f62e9e1b39.png">

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , thanks for the confirmation of your setting -- by the way, if you do an "ssh +X <IP address of GCP instance>", you can get the output from the "glxinfo | grep -i opengl" command to get the OpenGL info.

Hmm, looks like your setup is identical to mine (same versions from nvidia-smi), except for the MP version, and maybe the OpenGL version (the docs do mention that 3.1 should be okay though). I'll try updating to your version of MP and try again.

Also, just to confirm, you used the following build command and didn't include the "--config=cuda" option, is that right?

bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

**Comment by n-iwamoto** [comment]
Just tried building and running the GPU examples w/tag v0.9.2.1, and although it builds, when I run the example, I'm getting this error:

demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; RET_CHECK failure (mediapipe/examples/desktop/demo_run_graph_main_gpu.cc:76) capture.isOpened()

To confirm that this is due to the v0.9.2.1 tag, I pulled the v0.8.10 tag & built and ran it successfully (but no GPU utilization). I also tried v0.9.1, and it also gives the above error. 

How do I generate the graph that's required?

**Comment by ayushgdev** [comment]
@n-iwamoto You need to use the `--config=cuda` arg to use the ask Tensorflow to use GPU inference. Otherwise, MediaPipe does not know how to communicate the underlying Tensorflow layer that GPu inference is required. 
Around the issue of RET_CHECK failure, it indicates that the opencv is unable to open a stream with your video file. Check if the video path is correct or not in the input_video_file args.

**Comment by n-iwamoto** [comment]
@ayushgdev Got it, thanks for the clarification on the need to use the --config=cuda option, since the instructions didn't mention it:

https://google.github.io/mediapipe/getting_started/cpp.html

I'll try setting up to use the cuda compile option. Was having some problem w/it earlier, but hadn't used the GCP option you mentioned.

On the runtime error, yeah, my bad; I think I was too tired last night and missed it. It builds & runs now, though w/out GPU utilization. Sounds like the cuda build option was the necessary piece. I'll keep you posted

**Comment by n-iwamoto** [comment]
Hmm, I'm following the instructions from here (for T4):

https://cloud.google.com/compute/docs/gpus/install-drivers-gpu

But because CUDA 11.7 is already installed in GCP (looks like yours has it installed also from the nvidia-smi output), the "apt install cuda" is saying that a newer version is already installed. Did you run into this problem?

ls  /usr/local/cuda-11
cuda-11/   cuda-11.7/

**Comment by ayushgdev** [comment]
Hello @n-iwamoto 
No I did not encounter this issue. I can suggest you can check the alternative installation method using the official [Nvidia Drivers website](https://www.nvidia.com/Download/index.aspx?lang=en-us) _with fresh VM setup_. Choose Data Center/Tesla in it, fill in other details and it should give a link to a ".run" file. you can execute the file with commands 
```
sudo apt purge nvidia-*
sudo wget <link>
sudo sh file_name.run
```
That will include cuda as well. But cuDNN you have to downloads separately as usual.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , okay, I started again w/a clean new GCP instance (18.04 w/T4 GPU) using your link above to the CUDA 10.1 Driver version:

https://www.nvidia.com/Download/index.aspx?lang=en-us

Executed the commands you mentioned, and installed CUDA Toolkit 10.1 & cudnn v8.7.  I then followed the instructions from here:

https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop

and started the build:

bazel build -c opt --config=cuda --spawn_strategy=local \
    --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/object_detection:object_detection_tensorflow

but got a build error which indicated I needed to add a new build option (experimental_cc_shared_library):

bazel build -c opt --experimental_cc_shared_library --config=cuda --spawn_strategy=local     --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS     mediapipe/examples/desktop/object_detection:object_detection_tensorflow

After which it continued building for quite a while, but now I'm getting this build error. 

In file included from external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas_utils.cc:16:
external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_blas_utils.h:35:1: error: 'cublasComputeType_t' does not name a type; did you mean 'cublasDataType_t'?

I'm sure I must just be using the wrong configuration or something; don't imagine that you've run into these.

Any chance I can take a look at your GCP instance to see how it differs from mine?

**Comment by ayushgdev** [comment]
@n-iwamoto Unfortunately we cannot disclose the GCP instance since it is in house workspace. Also, the experimental_cc_shared_library was needed at our end to make it work. 
The new `cublasDataType_t` error is not encountered at our end.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev, yeah, I assumed as much, no worries. 

I'll try again tomorrow & document all the versions of things that I've installed (tried several variations), but they all are failing the build w/various errors (though similar to the one above) using this build command:

bazel build -c opt --experimental_cc_shared_library --config=cuda --spawn_strategy=local --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/object_detection:object_detection_tensorflow

Since this is all supposed to build correctly, I'm presuming I'm using the wrong combination of versions of something.

**Comment by ayushgdev** [comment]
Seems like the case here @n-iwamoto . GPU setup with any ML Library is very difficult to work as it requires combination of plethora of libraries, each having a particular version requirement. Even the sequence in which the deps are installed matter in a few cases. 
From our end, we will start discussing if we can improve the documentation to help in smooth setup for MediaPipe GPU usage, have it all together at one place, because right now we are pointing to different external websites for parts of the setup instructions as well; which incurs some setup effort for the users. But this will surely take time and we cannot commit any timeline.

**Comment by n-iwamoto** [comment]
@ayushgdev I had done previous searches for MediaPipe GPU example not using GPU, but hadn't seen this link until recently:

https://dev.classmethod.jp/articles/mediapipe-install-on-aws-ec2-with-gpu-english/

The author tested the same things I reported initially, except that he was able to get the GPU to be used (w/out the --config=cuda param), but was also using much older versions that I was. I tried using the steps he outlined in the post, but on a GCP instance vs AWS, but the versions were too old, and couldn't be pulled down.

What was very interesting to me was that he was able to use this build syntax and it worked:

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_gpu

So at least at one time in the past, this worked over OpenGL w/out using CUDA. 

Any ideas of what might have happened between this older version and now?

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , big breakthrough -- got the C++ GPU example working (i.e. it's now using the GPU):

https://developers.google.com/mediapipe/framework/getting_started/cpp

I tried it on an AWS EC2 instance, but it initially failed the same way (i.e. no GPU use). However, after changing a couple of things, including a tip from the link above, I got it working:

https://dev.classmethod.jp/articles/mediapipe-install-on-aws-ec2-with-gpu-english/

I just tried it using one of the GCP instances I had lying around, and after doing the couple of changes, I can also now get the GPU working.

I'll try a few more tests on the GCP instance, and then document what I found.

**Comment by ayushgdev** [comment]
@n-iwamoto Glad to know it has finally worked for you. Do share the details on the solution since we are also brainstorming why with all the correct configurations a user can face such an issue.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev, here are some notes of changes I had to do to make both the OpenGL & CUDA build options work for the C++ GPU example:

https://google.github.io/mediapipe/getting_started/cpp.html

Notes (used Ubuntu 18.04):
1. w/older MP versions (e.g. I started w/v0.8.10), must use > Bazel version 5.2.0 and gcc v8.x or build will fail
2. used ssh -X <GCP instance IP address>, since it was needed for glxinfo | grep -i opengl per the documentation (https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop)
3. More importantly though, when I used "ssh -X," I was able to run the GPU C++ examples above w/out errors (using just ssh, the run failed). However, the GPU wasn't being used when I ran the example. Unfortunately as it turns out, the "ssh -X" is what was causing the GPU to not be used.
4. In order for the run to not fail when using just "ssh", I used the information from the link above (https://dev.classmethod.jp/articles/mediapipe-install-on-aws-ec2-with-gpu-english/) to fix the build errors:
`diff --git a/mediapipe/gpu/gl_context_egl.cc b/mediapipe/gpu/gl_context_egl.cc
index f8784bbb..1e255806 100644
--- a/mediapipe/gpu/gl_context_egl.cc
+++ b/mediapipe/gpu/gl_context_egl.cc
@@ -125,7 +125,7 @@ absl::Status GlContext::CreateContextInternal(EGLContext share_context,
 #ifdef MEDIAPIPE_OMIT_EGL_WINDOW_BIT
       EGL_PBUFFER_BIT,
 #else
-      EGL_PBUFFER_BIT | EGL_WINDOW_BIT,
+      EGL_PBUFFER_BIT,
 #endif
       EGL_RED_SIZE, 8,
       EGL_GREEN_SIZE, 8,` 
5. This was the runtime error that required the above fix:
`demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
demo_run_graph_main_gpu.cc:62] Initialize the GPU.
gl_context_egl.cc:84] Successfully initialized EGL. Major : 1 Minor: 5
gl_context_egl.cc:183] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request.
gl_context_egl.cc:184] Fall back on OpenGL ES 2.
demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request.`
6. So w/the change above, and using just "ssh", the GPU started being utilized

Notes to use CUDA build option for the C++ GPU examples:
1. Used the following to build w/CUDA:
`bazel build -c opt --experimental_cc_shared_library --config=cuda --spawn_strategy=local  --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11  mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu`
2. The following change was required as well:
`diff --git a/mediapipe/framework/tool/BUILD b/mediapipe/framework/tool/BUILD
index 56ca0dc6..2c01ffdd 100644
--- a/mediapipe/framework/tool/BUILD
+++ b/mediapipe/framework/tool/BUILD
@@ -110,6 +110,7 @@ cc_binary(
     name = "encode_as_c_string",
     srcs = ["encode_as_c_string.cc"],
     visibility = ["//visibility:public"],
+    linkopts = ["-lm"],
     deps = [
         "@com_google_absl//absl/strings",
     ],`
3. After making the changes to the gl_context_egl.cc file, and "ssh", the build worked & used the GPU
4. I was never able to build the CUDA example here (https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop)

I tried building and running the face_detection example w/GPU:

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11   mediapipe/examples/desktop/face_detection:face_detection_full_range_gpu

but got a runtime error "Unable to find Calculator "FaceDetectionFullRangeGpu"". Any hints on how to get this to work? I tried modifying modules/face_detection/face_detection_full_range_gpu.pbtxt & examples/desktop/face_detection/BUILD, but still got the same error.

**Comment by n-iwamoto** [comment]
Hi @ayushgdev , that'll be great to have help on getting up to speed easier for newbies. For example, from my question above, it would be good to be able to run some of the other example (face detection in my case):

I tried building and running the face_detection example w/GPU:

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/face_detection:face_detection_full_range_gpu

but got a runtime error "Unable to find Calculator "FaceDetectionFullRangeGpu"". Any hints on how to get this to work? I tried modifying modules/face_detection/face_detection_full_range_gpu.pbtxt & examples/desktop/face_detection/BUILD, but still got the same error.

I could create this as a separate issue if you want, and if so, you can close this one out. 

Thanks again for all the help, it was appreciated!

**Comment by ayushgdev** [comment]
Hello @n-iwamoto 
Always happy to help. However, to keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one?
This helps community and us to search the issues better in concise manner.

**Comment by n-iwamoto** [comment]
HI @ayushgdev , will do, and thanks again for the help, it was appreciated!
